"""Information about all of the Cards."""

from __future__ import annotations

from typing import Any

from companion.util_classes import Expansions, Neighbourhood, Scenarios, Terror

__all__ = ["CODEX_CARDS", "EVENT_CARDS", "HEADLINE_CARDS", "NEIGHBOURHOOD_CARDS", "TERROR_CARDS"]


NEIGHBOURHOOD_CARDS: dict[Neighbourhood, Any] = {
    Neighbourhood.DOWNTOWN: {
        Expansions.BASE: [f"downtown_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"downtown_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [f"downtown_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"downtown_soto_{index}" for index in range(1, 3)],
        "back": "downtown_back",
    },
    Neighbourhood.EASTTOWN: {
        Expansions.BASE: [f"easttown_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"easttown_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [f"easttown_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"easttown_soto_{index}" for index in range(1, 3)],
        "back": "easttown_back",
    },
    Neighbourhood.MERCHANT_DISTRICT: {
        Expansions.BASE: [f"merchant_district_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"merchant_district_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"merchant_district_soto_{index}" for index in range(1, 3)],
        "back": "merchant_district_back",
    },
    Neighbourhood.MISKATONIC_UNIVERSITY: {
        Expansions.BASE: [f"miskatonic_university_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"miskatonic_university_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"miskatonic_university_soto_{index}" for index in range(1, 3)],
        "back": "miskatonic_university_back",
    },
    Neighbourhood.NORTHSIDE: {
        Expansions.BASE: [f"northside_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"northside_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [f"northside_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"northside_soto_{index}" for index in range(1, 3)],
        "back": "northside_back",
    },
    Neighbourhood.RIVERTOWN: {
        Expansions.BASE: [f"rivertown_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"rivertown_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [f"rivertown_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"rivertown_soto_{index}" for index in range(1, 3)],
        "back": "rivertown_back",
    },
    Neighbourhood.SOUTHSIDE: {
        Expansions.BASE: [f"southside_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"southside_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [f"southside_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"southside_soto_{index}" for index in range(1, 3)],
        "back": "southside_back",
    },
    Neighbourhood.UPTOWN: {
        Expansions.BASE: [f"uptown_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"uptown_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [f"uptown_udw_{index}" for index in range(1, 3)],
        Expansions.SECRETS_OF_THE_ORDER: [f"uptown_soto_{index}" for index in range(1, 3)],
        "back": "uptown_back",
    },
    Neighbourhood.THE_STREETS: {
        Expansions.BASE: [f"the_streets_{index}" for index in range(1, 9)],
        Expansions.DEAD_OF_NIGHT: [f"the_streets_don_{index}" for index in range(1, 9)],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "the_streets_back",
    },
    Neighbourhood.CENTRAL_KINGSPORT: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"central_kingsport_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "central_kingsport_back",
    },
    Neighbourhood.INNSMOUTH_SHORE: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"innsmouth_shore_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "innsmouth_shore_back",
    },
    Neighbourhood.INNSMOUTH_VILLAGE: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"innsmouth_village_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "innsmouth_village_back",
    },
    Neighbourhood.KINGSPORT_HARBOR: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"kingsport_harbor_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "kingsport_harbor_back",
    },
    Neighbourhood.TRAVEL_ROUTES: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"travel_routes_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "travel_routes_back",
    },
    Neighbourhood.DEVIL_REEF: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"devil_reef_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "devil_reef_back",
    },
    Neighbourhood.STRANGE_HIGH_HOUSE: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"strange_high_house_{index}" for index in range(1, 9)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "strange_high_house_back",
    },
    Neighbourhood.FRENCH_HILL: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [f"french_hill_{index}" for index in range(1, 9)],
        "back": "french_hill_back",
    },
    Neighbourhood.THE_UNDERWORLD: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [f"the_underworld_{index}" for index in range(1, 9)],
        "back": "the_underworld_back",
    },
    Neighbourhood.THRESHOLDS: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [f"thresholds_{index}" for index in range(1, 7)],
        "back": "thresholds_back",
    },
    Neighbourhood.THE_UNNAMABLE: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [f"the_unnamable_{index}" for index in range(1, 9)],
        "back": "the_unnamable_back",
    },
    Neighbourhood.WITCH_HOUSE: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [f"witch_house_{index}" for index in range(1, 9)],
        "back": "witch_house_back",
    },
    Neighbourhood.FRACTURED_REALITY: {
        Expansions.BASE: [f"fractured_reality_{index}" for index in range(1, 13)],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "fractured_reality_back",
    },
    Neighbourhood.LOST_SOULS: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [f"lost_souls_{index}" for index in range(1, 13)],
        "back": "lost_souls_back",
    },
    Neighbourhood.NIGHTMARE_BREACH: {
        Expansions.BASE: [f"nightmare_breach_{index}" for index in range(1, 13)],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "nightmare_breach_back",
    },
    Neighbourhood.TEMPORAL_FISSURE: {
        Expansions.BASE: [f"temporal_fissure_{index}" for index in range(1, 13)],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "temporal_fissure_back",
    },
    Neighbourhood.VISIONS_OF_THE_MOON: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [],
        Expansions.UNDER_DARK_WAVES: [f"visions_of_the_moon_{index}" for index in range(1, 13)],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "visions_of_the_moon_back",
    },
    Neighbourhood.YUGGOTH_EMERGENT: {
        Expansions.BASE: [],
        Expansions.DEAD_OF_NIGHT: [f"yuggoth_emergent_{index}" for index in range(1, 13)],
        Expansions.UNDER_DARK_WAVES: [],
        Expansions.SECRETS_OF_THE_ORDER: [],
        "back": "yuggoth_emergent_back",
    },
}


TERROR_CARDS: dict[Terror, Any] = {
    Terror.FEEDING_FRENZY: {
        "face": [f"feeding_frenzy_{index}" for index in range(1, 13)],
        "back": "feeding_frenzy_back",
    },
    Terror.FROZEN_CITY: {
        "face": [f"frozen_city_{index}" for index in range(1, 13)],
        "back": "frozen_city_back",
    },
}

HEADLINE_CARDS: dict[Any, Any] = {
    Expansions.BASE: [f"headlines_{index}" for index in range(1, 33)],
    Expansions.DEAD_OF_NIGHT: [f"headlines_don_{index}" for index in range(33, 40)],
    Expansions.UNDER_DARK_WAVES: [f"headlines_udw_{index}" for index in range(40, 44)],
    Expansions.SECRETS_OF_THE_ORDER: [f"headlines_soto_{index}" for index in range(44, 48)],
    "back": "headlines_back",
}

CODEX_CARDS = {index: {"face": f"codex_{index}_face", "back": f"codex_{index}_back"} for index in range(1, 166)}

EVENT_CARDS = {
    Scenarios.APPROACH_OF_AZATHOTH: [
        {"face": "approach_of_azathoth_1", "back": "easttown_back"},
        {"face": "approach_of_azathoth_2", "back": "rivertown_back"},
        {"face": "approach_of_azathoth_3", "back": "rivertown_back"},
        {"face": "approach_of_azathoth_4", "back": "easttown_back"},
        {"face": "approach_of_azathoth_5", "back": "downtown_back"},
        {"face": "approach_of_azathoth_6", "back": "northside_back"},
        {"face": "approach_of_azathoth_7", "back": "easttown_back"},
        {"face": "approach_of_azathoth_8", "back": "merchant_district_back"},
        {"face": "approach_of_azathoth_9", "back": "northside_back"},
        {"face": "approach_of_azathoth_10", "back": "merchant_district_back"},
        {"face": "approach_of_azathoth_11", "back": "downtown_back"},
        {"face": "approach_of_azathoth_12", "back": "merchant_district_back"},
        {"face": "approach_of_azathoth_13", "back": "northside_back"},
        {"face": "approach_of_azathoth_14", "back": "merchant_district_back"},
        {"face": "approach_of_azathoth_15", "back": "northside_back"},
        {"face": "approach_of_azathoth_16", "back": "downtown_back"},
        {"face": "approach_of_azathoth_17", "back": "northside_back"},
        {"face": "approach_of_azathoth_18", "back": "rivertown_back"},
        {"face": "approach_of_azathoth_19", "back": "easttown_back"},
        {"face": "approach_of_azathoth_20", "back": "merchant_district_back"},
        {"face": "approach_of_azathoth_21", "back": "rivertown_back"},
        {"face": "approach_of_azathoth_22", "back": "merchant_district_back"},
        {"face": "approach_of_azathoth_23", "back": "downtown_back"},
        {"face": "approach_of_azathoth_24", "back": "northside_back"},
    ],
    Scenarios.FEAST_FOR_UMORDHOTH: [
        {"face": "feast_for_umordhoth_1", "back": "downtown_back"},
        {"face": "feast_for_umordhoth_2", "back": "downtown_back"},
        {"face": "feast_for_umordhoth_3", "back": "downtown_back"},
        {"face": "feast_for_umordhoth_4", "back": "downtown_back"},
        {"face": "feast_for_umordhoth_5", "back": "easttown_back"},
        {"face": "feast_for_umordhoth_6", "back": "easttown_back"},
        {"face": "feast_for_umordhoth_7", "back": "easttown_back"},
        {"face": "feast_for_umordhoth_8", "back": "easttown_back"},
        {"face": "feast_for_umordhoth_9", "back": "rivertown_back"},
        {"face": "feast_for_umordhoth_10", "back": "rivertown_back"},
        {"face": "feast_for_umordhoth_11", "back": "rivertown_back"},
        {"face": "feast_for_umordhoth_12", "back": "rivertown_back"},
        {"face": "feast_for_umordhoth_13", "back": "rivertown_back"},
        {"face": "feast_for_umordhoth_14", "back": "rivertown_back"},
        {"face": "feast_for_umordhoth_15", "back": "southside_back"},
        {"face": "feast_for_umordhoth_16", "back": "southside_back"},
        {"face": "feast_for_umordhoth_17", "back": "southside_back"},
        {"face": "feast_for_umordhoth_18", "back": "southside_back"},
        {"face": "feast_for_umordhoth_19", "back": "uptown_back"},
        {"face": "feast_for_umordhoth_20", "back": "uptown_back"},
        {"face": "feast_for_umordhoth_21", "back": "uptown_back"},
        {"face": "feast_for_umordhoth_22", "back": "uptown_back"},
        {"face": "feast_for_umordhoth_23", "back": "uptown_back"},
        {"face": "feast_for_umordhoth_24", "back": "uptown_back"},
    ],
    Scenarios.VEIL_OF_TWILIGHT: [
        {"face": "veil_of_twilight_1", "back": "miskatonic_university_back"},
        {"face": "veil_of_twilight_2", "back": "miskatonic_university_back"},
        {"face": "veil_of_twilight_3", "back": "miskatonic_university_back"},
        {"face": "veil_of_twilight_4", "back": "miskatonic_university_back"},
        {"face": "veil_of_twilight_5", "back": "miskatonic_university_back"},
        {"face": "veil_of_twilight_6", "back": "northside_back"},
        {"face": "veil_of_twilight_7", "back": "northside_back"},
        {"face": "veil_of_twilight_8", "back": "northside_back"},
        {"face": "veil_of_twilight_9", "back": "northside_back"},
        {"face": "veil_of_twilight_10", "back": "northside_back"},
        {"face": "veil_of_twilight_11", "back": "northside_back"},
        {"face": "veil_of_twilight_12", "back": "rivertown_back"},
        {"face": "veil_of_twilight_13", "back": "rivertown_back"},
        {"face": "veil_of_twilight_14", "back": "rivertown_back"},
        {"face": "veil_of_twilight_15", "back": "rivertown_back"},
        {"face": "veil_of_twilight_16", "back": "rivertown_back"},
        {"face": "veil_of_twilight_17", "back": "southside_back"},
        {"face": "veil_of_twilight_18", "back": "southside_back"},
        {"face": "veil_of_twilight_19", "back": "southside_back"},
        {"face": "veil_of_twilight_20", "back": "southside_back"},
        {"face": "veil_of_twilight_21", "back": "uptown_back"},
        {"face": "veil_of_twilight_22", "back": "uptown_back"},
        {"face": "veil_of_twilight_23", "back": "uptown_back"},
        {"face": "veil_of_twilight_24", "back": "uptown_back"},
    ],
    Scenarios.ECHOES_OF_THE_DEEP: [
        {"face": "echoes_of_the_deep_1", "back": "downtown_back"},
        {"face": "echoes_of_the_deep_2", "back": "downtown_back"},
        {"face": "echoes_of_the_deep_3", "back": "downtown_back"},
        {"face": "echoes_of_the_deep_4", "back": "downtown_back"},
        {"face": "echoes_of_the_deep_5", "back": "merchant_district_back"},
        {"face": "echoes_of_the_deep_6", "back": "merchant_district_back"},
        {"face": "echoes_of_the_deep_7", "back": "merchant_district_back"},
        {"face": "echoes_of_the_deep_8", "back": "merchant_district_back"},
        {"face": "echoes_of_the_deep_9", "back": "merchant_district_back"},
        {"face": "echoes_of_the_deep_10", "back": "merchant_district_back"},
        {"face": "echoes_of_the_deep_11", "back": "miskatonic_university_back"},
        {"face": "echoes_of_the_deep_12", "back": "miskatonic_university_back"},
        {"face": "echoes_of_the_deep_13", "back": "miskatonic_university_back"},
        {"face": "echoes_of_the_deep_14", "back": "miskatonic_university_back"},
        {"face": "echoes_of_the_deep_15", "back": "miskatonic_university_back"},
        {"face": "echoes_of_the_deep_16", "back": "northside_back"},
        {"face": "echoes_of_the_deep_17", "back": "northside_back"},
        {"face": "echoes_of_the_deep_18", "back": "northside_back"},
        {"face": "echoes_of_the_deep_19", "back": "northside_back"},
        {"face": "echoes_of_the_deep_20", "back": "rivertown_back"},
        {"face": "echoes_of_the_deep_21", "back": "rivertown_back"},
        {"face": "echoes_of_the_deep_22", "back": "rivertown_back"},
        {"face": "echoes_of_the_deep_23", "back": "rivertown_back"},
        {"face": "echoes_of_the_deep_24", "back": "rivertown_back"},
    ],
    Scenarios.SHOTS_IN_THE_DARK: [
        {"face": "shots_in_the_dark_1", "back": "downtown_back"},
        {"face": "shots_in_the_dark_2", "back": "downtown_back"},
        {"face": "shots_in_the_dark_3", "back": "downtown_back"},
        {"face": "shots_in_the_dark_4", "back": "downtown_back"},
        {"face": "shots_in_the_dark_5", "back": "downtown_back"},
        {"face": "shots_in_the_dark_6", "back": "downtown_back"},
        {"face": "shots_in_the_dark_7", "back": "easttown_back"},
        {"face": "shots_in_the_dark_8", "back": "easttown_back"},
        {"face": "shots_in_the_dark_9", "back": "easttown_back"},
        {"face": "shots_in_the_dark_10", "back": "easttown_back"},
        {"face": "shots_in_the_dark_11", "back": "merchant_district_back"},
        {"face": "shots_in_the_dark_12", "back": "merchant_district_back"},
        {"face": "shots_in_the_dark_13", "back": "merchant_district_back"},
        {"face": "shots_in_the_dark_14", "back": "merchant_district_back"},
        {"face": "shots_in_the_dark_15", "back": "merchant_district_back"},
        {"face": "shots_in_the_dark_16", "back": "merchant_district_back"},
        {"face": "shots_in_the_dark_17", "back": "northside_back"},
        {"face": "shots_in_the_dark_18", "back": "northside_back"},
        {"face": "shots_in_the_dark_19", "back": "northside_back"},
        {"face": "shots_in_the_dark_20", "back": "northside_back"},
        {"face": "shots_in_the_dark_21", "back": "rivertown_back"},
        {"face": "shots_in_the_dark_22", "back": "rivertown_back"},
        {"face": "shots_in_the_dark_23", "back": "rivertown_back"},
        {"face": "shots_in_the_dark_24", "back": "rivertown_back"},
    ],
    Scenarios.SILENCE_OF_TSATHOGGUA: [
        {"face": "silence_of_tsathoggua_1", "back": "merchant_district_back"},
        {"face": "silence_of_tsathoggua_2", "back": "merchant_district_back"},
        {"face": "silence_of_tsathoggua_3", "back": "merchant_district_back"},
        {"face": "silence_of_tsathoggua_4", "back": "merchant_district_back"},
        {"face": "silence_of_tsathoggua_5", "back": "miskatonic_university_back"},
        {"face": "silence_of_tsathoggua_6", "back": "miskatonic_university_back"},
        {"face": "silence_of_tsathoggua_7", "back": "miskatonic_university_back"},
        {"face": "silence_of_tsathoggua_8", "back": "miskatonic_university_back"},
        {"face": "silence_of_tsathoggua_9", "back": "miskatonic_university_back"},
        {"face": "silence_of_tsathoggua_10", "back": "northside_back"},
        {"face": "silence_of_tsathoggua_11", "back": "northside_back"},
        {"face": "silence_of_tsathoggua_12", "back": "northside_back"},
        {"face": "silence_of_tsathoggua_13", "back": "northside_back"},
        {"face": "silence_of_tsathoggua_14", "back": "rivertown_back"},
        {"face": "silence_of_tsathoggua_15", "back": "rivertown_back"},
        {"face": "silence_of_tsathoggua_16", "back": "rivertown_back"},
        {"face": "silence_of_tsathoggua_17", "back": "rivertown_back"},
        {"face": "silence_of_tsathoggua_18", "back": "rivertown_back"},
        {"face": "silence_of_tsathoggua_19", "back": "uptown_back"},
        {"face": "silence_of_tsathoggua_20", "back": "uptown_back"},
        {"face": "silence_of_tsathoggua_21", "back": "uptown_back"},
        {"face": "silence_of_tsathoggua_22", "back": "uptown_back"},
        {"face": "silence_of_tsathoggua_23", "back": "uptown_back"},
        {"face": "silence_of_tsathoggua_24", "back": "uptown_back"},
    ],
    Scenarios.DREAMS_OF_RLYEH: [
        {"face": "dreams_of_rlyeh_1", "back": "central_kingsport_back"},
        {"face": "dreams_of_rlyeh_2", "back": "central_kingsport_back"},
        {"face": "dreams_of_rlyeh_3", "back": "central_kingsport_back"},
        {"face": "dreams_of_rlyeh_4", "back": "central_kingsport_back"},
        {"face": "dreams_of_rlyeh_5", "back": "innsmouth_shore_back"},
        {"face": "dreams_of_rlyeh_6", "back": "innsmouth_shore_back"},
        {"face": "dreams_of_rlyeh_7", "back": "innsmouth_shore_back"},
        {"face": "dreams_of_rlyeh_8", "back": "innsmouth_shore_back"},
        {"face": "dreams_of_rlyeh_9", "back": "innsmouth_village_back"},
        {"face": "dreams_of_rlyeh_10", "back": "innsmouth_village_back"},
        {"face": "dreams_of_rlyeh_11", "back": "innsmouth_village_back"},
        {"face": "dreams_of_rlyeh_12", "back": "innsmouth_village_back"},
        {"face": "dreams_of_rlyeh_13", "back": "kingsport_harbor_back"},
        {"face": "dreams_of_rlyeh_14", "back": "kingsport_harbor_back"},
        {"face": "dreams_of_rlyeh_15", "back": "kingsport_harbor_back"},
        {"face": "dreams_of_rlyeh_16", "back": "kingsport_harbor_back"},
        {"face": "dreams_of_rlyeh_17", "back": "miskatonic_university_back"},
        {"face": "dreams_of_rlyeh_18", "back": "miskatonic_university_back"},
        {"face": "dreams_of_rlyeh_19", "back": "miskatonic_university_back"},
        {"face": "dreams_of_rlyeh_20", "back": "rivertown_back"},
        {"face": "dreams_of_rlyeh_21", "back": "rivertown_back"},
        {"face": "dreams_of_rlyeh_22", "back": "rivertown_back"},
        {"face": "dreams_of_rlyeh_23", "back": "rivertown_back"},
        {"face": "dreams_of_rlyeh_24", "back": "southside_back"},
        {"face": "dreams_of_rlyeh_25", "back": "southside_back"},
        {"face": "dreams_of_rlyeh_26", "back": "southside_back"},
        {"face": "dreams_of_rlyeh_27", "back": "southside_back"},
        {"face": "dreams_of_rlyeh_28", "back": "southside_back"},
        {"face": "dreams_of_rlyeh_29", "back": "uptown_back"},
        {"face": "dreams_of_rlyeh_30", "back": "uptown_back"},
        {"face": "dreams_of_rlyeh_31", "back": "uptown_back"},
        {"face": "dreams_of_rlyeh_32", "back": "uptown_back"},
    ],
    Scenarios.THE_PALE_LANTERN: [
        {"face": "the_pale_lantern_1", "back": "central_kingsport_back"},
        {"face": "the_pale_lantern_2", "back": "central_kingsport_back"},
        {"face": "the_pale_lantern_3", "back": "central_kingsport_back"},
        {"face": "the_pale_lantern_4", "back": "central_kingsport_back"},
        {"face": "the_pale_lantern_5", "back": "central_kingsport_back"},
        {"face": "the_pale_lantern_6", "back": "downtown_back"},
        {"face": "the_pale_lantern_7", "back": "downtown_back"},
        {"face": "the_pale_lantern_8", "back": "downtown_back"},
        {"face": "the_pale_lantern_9", "back": "downtown_back"},
        {"face": "the_pale_lantern_10", "back": "downtown_back"},
        {"face": "the_pale_lantern_11", "back": "kingsport_harbor_back"},
        {"face": "the_pale_lantern_12", "back": "kingsport_harbor_back"},
        {"face": "the_pale_lantern_13", "back": "kingsport_harbor_back"},
        {"face": "the_pale_lantern_14", "back": "kingsport_harbor_back"},
        {"face": "the_pale_lantern_15", "back": "kingsport_harbor_back"},
        {"face": "the_pale_lantern_16", "back": "merchant_district_back"},
        {"face": "the_pale_lantern_17", "back": "merchant_district_back"},
        {"face": "the_pale_lantern_18", "back": "merchant_district_back"},
        {"face": "the_pale_lantern_19", "back": "merchant_district_back"},
        {"face": "the_pale_lantern_20", "back": "uptown_back"},
        {"face": "the_pale_lantern_21", "back": "uptown_back"},
        {"face": "the_pale_lantern_22", "back": "uptown_back"},
        {"face": "the_pale_lantern_23", "back": "uptown_back"},
        {"face": "the_pale_lantern_24", "back": "uptown_back"},
    ],
    Scenarios.TYRANTS_OF_RUIN: [
        {"face": "tyrants_of_ruin_1", "back": "easttown_back"},
        {"face": "tyrants_of_ruin_2", "back": "easttown_back"},
        {"face": "tyrants_of_ruin_3", "back": "easttown_back"},
        {"face": "tyrants_of_ruin_4", "back": "innsmouth_shore_back"},
        {"face": "tyrants_of_ruin_5", "back": "innsmouth_shore_back"},
        {"face": "tyrants_of_ruin_6", "back": "innsmouth_shore_back"},
        {"face": "tyrants_of_ruin_7", "back": "innsmouth_shore_back"},
        {"face": "tyrants_of_ruin_8", "back": "innsmouth_shore_back"},
        {"face": "tyrants_of_ruin_9", "back": "innsmouth_village_back"},
        {"face": "tyrants_of_ruin_10", "back": "innsmouth_village_back"},
        {"face": "tyrants_of_ruin_11", "back": "innsmouth_village_back"},
        {"face": "tyrants_of_ruin_12", "back": "innsmouth_village_back"},
        {"face": "tyrants_of_ruin_13", "back": "innsmouth_village_back"},
        {"face": "tyrants_of_ruin_14", "back": "miskatonic_university_back"},
        {"face": "tyrants_of_ruin_15", "back": "miskatonic_university_back"},
        {"face": "tyrants_of_ruin_16", "back": "miskatonic_university_back"},
        {"face": "tyrants_of_ruin_17", "back": "miskatonic_university_back"},
        {"face": "tyrants_of_ruin_18", "back": "northside_back"},
        {"face": "tyrants_of_ruin_19", "back": "northside_back"},
        {"face": "tyrants_of_ruin_20", "back": "northside_back"},
        {"face": "tyrants_of_ruin_21", "back": "southside_back"},
        {"face": "tyrants_of_ruin_22", "back": "southside_back"},
        {"face": "tyrants_of_ruin_23", "back": "southside_back"},
        {"face": "tyrants_of_ruin_24", "back": "southside_back"},
    ],
    Scenarios.ITHAQUAS_CHILDREN: [
        {"face": "ithaquas_children_1", "back": "central_kingsport_back"},
        {"face": "ithaquas_children_2", "back": "central_kingsport_back"},
        {"face": "ithaquas_children_3", "back": "central_kingsport_back"},
        {"face": "ithaquas_children_4", "back": "central_kingsport_back"},
        {"face": "ithaquas_children_5", "back": "downtown_back"},
        {"face": "ithaquas_children_6", "back": "downtown_back"},
        {"face": "ithaquas_children_7", "back": "downtown_back"},
        {"face": "ithaquas_children_8", "back": "easttown_back"},
        {"face": "ithaquas_children_9", "back": "easttown_back"},
        {"face": "ithaquas_children_10", "back": "easttown_back"},
        {"face": "ithaquas_children_11", "back": "innsmouth_shore_back"},
        {"face": "ithaquas_children_12", "back": "innsmouth_shore_back"},
        {"face": "ithaquas_children_13", "back": "innsmouth_shore_back"},
        {"face": "ithaquas_children_14", "back": "innsmouth_shore_back"},
        {"face": "ithaquas_children_15", "back": "northside_back"},
        {"face": "ithaquas_children_16", "back": "northside_back"},
        {"face": "ithaquas_children_17", "back": "northside_back"},
        {"face": "ithaquas_children_18", "back": "rivertown_back"},
        {"face": "ithaquas_children_19", "back": "rivertown_back"},
        {"face": "ithaquas_children_20", "back": "rivertown_back"},
        {"face": "ithaquas_children_21", "back": "rivertown_back"},
        {"face": "ithaquas_children_22", "back": "southside_back"},
        {"face": "ithaquas_children_23", "back": "southside_back"},
        {"face": "ithaquas_children_24", "back": "southside_back"},
    ],
    Scenarios.THE_DEAD_CRY_OUT: [
        {"face": "the_dead_cry_out_1", "back": "easttown_back"},
        {"face": "the_dead_cry_out_2", "back": "easttown_back"},
        {"face": "the_dead_cry_out_3", "back": "easttown_back"},
        {"face": "the_dead_cry_out_4", "back": "french_hill_back"},
        {"face": "the_dead_cry_out_5", "back": "french_hill_back"},
        {"face": "the_dead_cry_out_6", "back": "french_hill_back"},
        {"face": "the_dead_cry_out_7", "back": "french_hill_back"},
        {"face": "the_dead_cry_out_8", "back": "miskatonic_university_back"},
        {"face": "the_dead_cry_out_9", "back": "miskatonic_university_back"},
        {"face": "the_dead_cry_out_10", "back": "miskatonic_university_back"},
        {"face": "the_dead_cry_out_11", "back": "miskatonic_university_back"},
        {"face": "the_dead_cry_out_12", "back": "northside_back"},
        {"face": "the_dead_cry_out_13", "back": "northside_back"},
        {"face": "the_dead_cry_out_14", "back": "northside_back"},
        {"face": "the_dead_cry_out_15", "back": "northside_back"},
        {"face": "the_dead_cry_out_16", "back": "southside_back"},
        {"face": "the_dead_cry_out_17", "back": "southside_back"},
        {"face": "the_dead_cry_out_18", "back": "southside_back"},
        {"face": "the_dead_cry_out_19", "back": "southside_back"},
        {"face": "the_dead_cry_out_20", "back": "the_underworld_back"},
        {"face": "the_dead_cry_out_21", "back": "the_underworld_back"},
        {"face": "the_dead_cry_out_22", "back": "the_underworld_back"},
        {"face": "the_dead_cry_out_23", "back": "the_underworld_back"},
        {"face": "the_dead_cry_out_24", "back": "the_underworld_back"},
        {"face": "the_dead_cry_out_25", "back": "uptown_back"},
        {"face": "the_dead_cry_out_26", "back": "uptown_back"},
        {"face": "the_dead_cry_out_27", "back": "uptown_back"},
        {"face": "the_dead_cry_out_28", "back": "uptown_back"},
    ],
    Scenarios.THE_KEY_AND_THE_GATE: [
        {"face": "the_key_and_the_gate_1", "back": "easttown_back"},
        {"face": "the_key_and_the_gate_2", "back": "easttown_back"},
        {"face": "the_key_and_the_gate_3", "back": "easttown_back"},
        {"face": "the_key_and_the_gate_4", "back": "easttown_back"},
        {"face": "the_key_and_the_gate_5", "back": "easttown_back"},
        {"face": "the_key_and_the_gate_6", "back": "french_hill_back"},
        {"face": "the_key_and_the_gate_7", "back": "french_hill_back"},
        {"face": "the_key_and_the_gate_8", "back": "french_hill_back"},
        {"face": "the_key_and_the_gate_9", "back": "french_hill_back"},
        {"face": "the_key_and_the_gate_10", "back": "french_hill_back"},
        {"face": "the_key_and_the_gate_11", "back": "merchant_district_back"},
        {"face": "the_key_and_the_gate_12", "back": "merchant_district_back"},
        {"face": "the_key_and_the_gate_13", "back": "merchant_district_back"},
        {"face": "the_key_and_the_gate_14", "back": "rivertown_back"},
        {"face": "the_key_and_the_gate_15", "back": "rivertown_back"},
        {"face": "the_key_and_the_gate_16", "back": "rivertown_back"},
        {"face": "the_key_and_the_gate_17", "back": "rivertown_back"},
        {"face": "the_key_and_the_gate_18", "back": "the_underworld_back"},
        {"face": "the_key_and_the_gate_19", "back": "the_underworld_back"},
        {"face": "the_key_and_the_gate_20", "back": "the_underworld_back"},
        {"face": "the_key_and_the_gate_21", "back": "the_underworld_back"},
        {"face": "the_key_and_the_gate_22", "back": "uptown_back"},
        {"face": "the_key_and_the_gate_23", "back": "uptown_back"},
        {"face": "the_key_and_the_gate_24", "back": "uptown_back"},
        {"face": "the_key_and_the_gate_25", "back": "uptown_back"},
        {"face": "the_key_and_the_gate_26", "back": "uptown_back"},
        {"face": "the_key_and_the_gate_27", "back": "the_unnamable_back"},
        {"face": "the_key_and_the_gate_28", "back": "the_unnamable_back"},
    ],
    Scenarios.BOUND_TO_SERVE: [
        {"face": "bound_to_serve_1", "back": "downtown_back"},
        {"face": "bound_to_serve_2", "back": "downtown_back"},
        {"face": "bound_to_serve_3", "back": "downtown_back"},
        {"face": "bound_to_serve_4", "back": "french_hill_back"},
        {"face": "bound_to_serve_5", "back": "french_hill_back"},
        {"face": "bound_to_serve_6", "back": "french_hill_back"},
        {"face": "bound_to_serve_7", "back": "merchant_district_back"},
        {"face": "bound_to_serve_8", "back": "merchant_district_back"},
        {"face": "bound_to_serve_9", "back": "merchant_district_back"},
        {"face": "bound_to_serve_10", "back": "merchant_district_back"},
        {"face": "bound_to_serve_11", "back": "rivertown_back"},
        {"face": "bound_to_serve_12", "back": "rivertown_back"},
        {"face": "bound_to_serve_13", "back": "rivertown_back"},
        {"face": "bound_to_serve_14", "back": "rivertown_back"},
        {"face": "bound_to_serve_15", "back": "southside_back"},
        {"face": "bound_to_serve_16", "back": "southside_back"},
        {"face": "bound_to_serve_17", "back": "southside_back"},
        {"face": "bound_to_serve_18", "back": "southside_back"},
        {"face": "bound_to_serve_19", "back": "uptown_back"},
        {"face": "bound_to_serve_20", "back": "uptown_back"},
        {"face": "bound_to_serve_21", "back": "uptown_back"},
        {"face": "bound_to_serve_22", "back": "uptown_back"},
        {"face": "bound_to_serve_23", "back": "witch_house_back"},
        {"face": "bound_to_serve_24", "back": "witch_house_back"},
    ],
}
